# Generated by Django 5.1.5 on 2025-01-28 02:08

import django.db.models.deletion
import music_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0002_alter_track_album_alter_track_artist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-created_at'], 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterModelOptions(
            name='userlibrary',
            options={'ordering': ['-added_at'], 'verbose_name': 'Библиотека пользователя', 'verbose_name_plural': 'Библиотеки пользователей'},
        ),
        migrations.RemoveField(
            model_name='track',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='track',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='track',
            name='yandex_id',
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Длительность (сек)'),
        ),
        migrations.AddField(
            model_name='track',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(default='Unknown Artist', max_length=200, verbose_name='Исполнитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userlibrary',
            unique_together={('user', 'track')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=music_api.models.user_avatar_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
