# Generated by Django 5.1.5 on 2025-02-03 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0004_yandexaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yandexaccount',
            options={},
        ),
        migrations.RemoveField(
            model_name='yandexaccount',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='yandexaccount',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='yandexaccount',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yandexaccount',
            name='yandex_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
