# Generated by Django 5.1.5 on 2025-02-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0005_alter_yandexaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yandexaccount',
            options={'verbose_name': 'Яндекс аккаунт', 'verbose_name_plural': 'Яндекс аккаунты'},
        ),
        migrations.AddField(
            model_name='yandexaccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yandexaccount',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yandexaccount',
            name='yandex_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
