# Generated by Django 5.0 on 2025-04-30 13:07

import music_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0008_track_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='track_covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file_path',
            field=models.FileField(upload_to=music_api.models.track_file_path, verbose_name='Аудио файл'),
        ),
    ]
